"""empty message

Revision ID: 6eb9fc7d2bc7
Revises: 9da7dc99151f
Create Date: 2020-11-05 15:32:38.718303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb9fc7d2bc7'
down_revision = '9da7dc99151f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
